### ISSUE TITLE
Test all parameters

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#11]
Right now, the program will test only the last parameter, as in:

URL: http://example.com/index.php?id=123&bla=123&lol=5

only lol=5 will be tested by adding ` in the last part.
what about testing each parameter ?

**Comment by Ekultek** [comment]
Great idea! This will be added to the TODO list and I'll get working on it. However I can't guarantee that it will be released by the next update. Probably more around 1.0.7 when I release the advanced URL decoding.

**Comment by Ekultek** [comment]
RE-OPENED 09/08/2016

**Comment by Ekultek** [comment]
Currently testing a version of the parameters, it will add to every single parameter, will be editing it so that it will only try one parameter at a time

**Comment by Ekultek** [comment]
Done!
