### ISSUE TITLE
Using multiple SQL Injection symbols

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#12]
Right now I see you use `'`, it would give better results to use ` instead.

Also, using `;` and `--` would be interesting too.
how about trying again with different symbol if the check failed to produce SQL results ?

**Comment by Ekultek** [comment]
This will be done with the advanced decoding. Feel free to try and code your own ideas into whitewidow and contribute!

Leaving this open because I like the idea

**Comment by Ekultek** [comment]
I am a little interested to know what the `--` would do. As far as I know that's just used for comments in certain DB's?

**Comment by Ekultek** [comment]
Added and will be added with release of 1.0.6, you're going to like this release
