### ISSUE TITLE
Use Proxy

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#15]
So, Lets say I want to test the sites but not expose my self.
Right now using a proxy for all the program is problematic because google search doesn't like it.
A `--proxy=` option to be used when the actual connection to the sites is made would be awesome

**Comment by Ekultek** [comment]
As of right now you don't need a proxy, it uses random user agents, so Google thinks your someone else anyways. The only thing Google has is your IP. 
If you want further anomity I can add a proxy setting

**Comment by bararchy** [comment]
@Ekultek When a site is being checked, don't you connect to it directly to check the SQLi ?

**Comment by Ekultek** [comment]
Of course, but what I'm saying, is as long as the site thinks you're something else, I would assume you're safe. But of course I can add a proxy switch. I've been meaning to for awhile now.

**Comment by bararchy** [comment]
@Ekultek The site knows your IP, that's what they care about, even if You and I or other people who wish to do good using this tool the owner can legally act upon this as an attack.

This is why the google search should be direct (or maybe thinking about using DuckGoGo which allows searches from TOR), and the "checks" should go over using a proxy the user chooses.

**Comment by Ekultek** [comment]
So what you're saying is make a --proxy=PROXY flag?

**Comment by Ekultek** [comment]
Read the future updates: https://github.com/Ekultek/whitewidow/blob/master/README.md

**Comment by Ekultek** [comment]
RE-OPENED 09/08/2016

**Comment by Ekultek** [comment]
Alright so I added a proxy flag and the ability to use a proxy, however I don't have a good proxy to use, so I'll need some testers to tell me what the hell happens with it, it should work. I just don't wanna publish a release without knowing what's going to happen.

**Comment by Ekultek** [comment]
Closed, if it doesn't work then it doesn't work.
