### ISSUE TITLE
Seperate detection and testing stages.

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#16]
Using -d will do the google dork run, then, the program will ask if you wish to check the link or just to save them to SQL_TO_CHECK file (Dry Run).

**Comment by Ekultek** [comment]
That's a lot of prompting for input..

**Comment by bararchy** [comment]
Well, we can add --batch flag for no questions ;)

Sent with AquaMail for Android
http://www.aqua-mail.com

On April 18, 2016 2:49:32 PM Ekultek notifications@github.com wrote:

That's a lot of prompting for input..

##

**Comment by Ekultek** [comment]
I'd rather just keep it batch and have a --no-batch flag that will allow them to save to a temp file or something?

**Comment by Ekultek** [comment]
Project not maintained anymore.

**Comment by Ekultek** [comment]
RE-OPENED 09/08/2016

**Comment by Ekultek** [comment]
DONE!
