### ISSUE TITLE
Remove ' from Testing as it wont cuse SQL Injection to be detected

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#17]
For me (And my low knowledge of SQL) the `'` sign will never cause an SQL Injection to be detected.

Here is an Example:
![screenshot from 2016-04-18 10-48-36](https://cloud.githubusercontent.com/assets/1631073/14597254/3fa797c2-0554-11e6-9a1f-60f9074a040e.png)

You can see an SQLi has been detected (I did not confirm or checked it manually) but only using `, -- and ;

**Comment by Ekultek** [comment]
That's incorrect, an apostrophe is the most basic way of checking for vulnerability within a website.
