### ISSUE TITLE
Syntax error, unexpected tIDENTIFIER

### ISSUE THREAD

**Issue by nukeop** [Ekultek/whitewidow#25]
### Issue (be specific)
Running `ruby whitewidow.rb -d` results in a bunch of syntax errors. I have never touched ruby before but it looks to me like an incorrectly formatted string.

### Exact error message

```
$ ruby whitewidow.rb -d --dry-run
whitewidow.rb:66: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...      Hey now my friend, I know you're eager, I am also, but...
...                               ^
whitewidow.rb:67: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      either doesn't exist, or it's not in the di...
                    ^
whitewidow.rb:67: syntax error, unexpected keyword_or
      either doesn't exist, or it's not in the directory yo...
                              ^
whitewidow.rb:67: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...t in the directory you say it's in..
...                               ^
whitewidow.rb:72: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      Don't worry I'll wait!
           ^
whitewidow.rb:90: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  FORMAT.info("I'm searching for possible SQL v...
                  ^
whitewidow.rb:90: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
..."I'm searching for possible SQL vulnerable sites, using sear...
...                               ^
whitewidow.rb:90: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
... vulnerable sites, using search query #{query.chomp}")
...                               ^
whitewidow.rb:104: syntax error, unexpected keyword_do_block, expecting keyword_end
  url.links.each do |link|
```

### Steps to reproduce
1. Clone the respository
2. `cd whitewidow`
3. `sudo bundle install`
4. `ruby whitewidow.rb -d`

### Whitewidow version number
https://github.com/Ekultek/whitewidow/commit/c1247be438ec0c89f68ef7806eb2f473daefebf7

### Ruby version number
2.2.5p319

### Labels

  - [ ] Bug
- [ ] Enhancement
 - [x] Question

**Comment by Ekultek** [comment]
That's weird, give me a little bit

**Comment by Ekultek** [comment]
I need the version number run `ruby whitewidow.rb --credits`
Post the output

**Comment by nukeop** [comment]
That gives me the same syntax error, but inside whitewidow.rb I found the useragent string which says Whitewidow 1.5.0.2.

**Comment by Ekultek** [comment]
Just cloned my repo and ran your flags:

```
C:\>ruby whitewidow.rb -d --dry-run
   __      __.__    .__  __         __      __.__    .___
  /  \    /  \  |__ |__|/  |_  ____/  \    /  \__| __| _/______  _  __
  \   \/\/   /  |  \|  \   __\/ __ \   \/\/   /  |/ __ |/  _ \ \/ \/ /
   \        /|   Y  \  ||  | \  ___/\        /|  / /_/ (  <_> )     /
    \__/\  / |___|  /__||__|  \___  >\__/\  / |______ | \____/ \/\_/
         \/       \/              \/      \/           \/

[14:10:51 INFO] I'm searching for possible SQL vulnerable sites, using search query in
url:Art.php?id= title:login
[14:10:52 SUCCESS] Site found: http://go.speedbit.com/Search.aspx?q=Art.php?id=%20Site
%20.uk&related=1&s=DCFb
[14:10:54 SUCCESS] Site found: http://go.speedbit.com/Search.aspx?q=Art.php?id=%20Site
%20.uk&start=1&s=E1Vaya1
[14:10:54 SUCCESS] Site found: http://go.speedbit.com/Search.aspx?q=Art.php?id=%20Site
%20.uk&start=51
[14:10:54 SUCCESS] Site found: http://go.speedbit.com/Search.aspx%5C%5C?q=Inurl%20Art.
php?idm=%20Site%20Fr&related=1
[14:10:55 INFO] I've dumped possible vulnerable sites into C:/Users/thomas_j_perkins/D
esktop/whitewidow/tmp/SQL_sites_to_check.txt
Run the sites[Y/N]: n
[14:10:57 INFO] Sites saved to file, will not run scan now..

C:\>
```

I have a couple of things for you to try:
- Download the latest version of ruby: https://www.ruby-lang.org/en/downloads/
- Download the tar or zip here: https://github.com/Ekultek/whitewidow/releases/tag/1.5.0

I'm going to need some info to resolve this issue for you though,
- Run `ruby whitewidow.rb --credits` and tell me the version you have and type
- What OS are you using?
- Check if the gems installed correctly by running `gem list`
- Run `gem install bundler` and cd into whitewidows dir and run `bundle install`

Let me know that outcome of these

**Comment by Ekultek** [comment]
Found the problem, the squiggly heredoc was not introduced until Ruby version 2.3. You are running version 2.2.5, therefore it's failing with the squiggly heredocs (<<~).

To fix this you will need to download either 2.3 or the newest version. Closing the issue.

For more information read here: https://infinum.co/the-capsized-eight/articles/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

**Comment by Ekultek** [comment]
Second thought I'll keep this open for a couple days in case of questions

**Comment by nukeop** [comment]
Yes, that is correct, installing Ruby 2.3.1 solves the issue. Cheers.

**Comment by Ekultek** [comment]
For future reference I'll be catching the error and if it's thrown it'll specify what ruby version you'll need. Closing issue.

**Comment by Ekultek** [comment]
Make a new issue for an enhancement for this
