### ISSUE TITLE
Possible XSS searches along with SQL scanning

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#28]
This isn't really an issue, more of an idea that I would like some opinions on. 

This is entirely up to the community and is entirely your choice, should I create a search for XSS vulnerabilities? For example:

You will run something like `ruby whitewidow.rb -d --xss` it will scan for vulnerabilities like normal but will also check if a site is vulnerable to XSS scripting using a basic JS script or something, let me know what you think in the comments

**Comment by Ekultek** [comment]
I lied I'm going to do it

**Comment by Nazis** [comment]
sounds good my dude u are so kind

**Comment by Ekultek** [comment]
Well I'm reopening this because it's going to be a lot harder then originally intended. I can do it, but I would like to know if anyone has a specific way they would want it done? For example:

Use it as default with the `-d` flag, or use it as it's own section like you can choose to either search for XSS vulns while you search for SQL vulns, if a site is found to be SQL vuln then it'll skip XSS searching. If it's not SQL vuln it'll check if it's XSS vuln: `ruby whitewidow.rb -d --xss` so it'll do something along the lines of this:

```
[some time WARNING] http://this.site.com/php?id=1 is not vulnerable, checking for XSS vulns with <script>alert("TEST");</script>
[some time INFO] http://this.site.com/php?id=<script>alert("TEST");</script> is XSS vuln, dumped to xss_sites.LOG # or something
```

**Comment by Ekultek** [comment]
Will be done soon, probably around next major update
