### ISSUE TITLE
Cant Install WhiteWidow

### ISSUE THREAD

**Issue by Shazgul** [Ekultek/whitewidow#29]
### Before you create an issue please make sure that there are no issues that relate to your issue you are trying to create, if there is an issue that relates to this, please add a comment to that one and describe your specific problem
--

### Issue (be specific)

I cant do bundle install...

### Exact error message

bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing unf_ext 0.0.7.2 with native extensions
Using mime-types-data 3.2016.0521
Using net-http-digest_auth 1.4
Using net-http-persistent 2.9.4
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using ntlm-http 0.1.1
Using webrobots 0.1.2
Using netrc 0.11.0
Using bundler 1.13.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20161128-32376-14skn5funf_ext-0.0.7.2/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20161128-32376-v31vjj.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20161128-32376-14skn5funf_ext-0.0.7.2/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20161128-32376-14skn5funf_ext-0.0.7.2/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /tmp/bundler20161128-32376-14skn5funf_ext-0.0.7.2/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/gem_make.out

An error occurred while installing unf_ext (0.0.7.2), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.2'` succeeds before bundling.

### Labels

 - [ ] Bug
 - [ ] Enhancement
 - [x] Question
 - [ ] Email request

**Comment by Ekultek** [comment]
Try this:
`gem install mechanize`
Post the output

**Comment by Shazgul** [comment]
sudo gem install mechanize

Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Building native extensions.  This could take a while...
ERROR:  Error installing mechanize:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20161128-8285-drdj0d.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/gem_make.out

**Comment by Ekultek** [comment]
You need to download the development environment for ruby, you'll need ruby 2.3.0 at least for whitewidow so `sudo apt-get ruby2.3.0-dev`

**Comment by Ekultek** [comment]
I'll be adding some self troubleshooting steps for issues like this one. I'll push it sometime tonight

**Comment by Shazgul** [comment]
ruby2.3 plus ruby2.3-dev is installed, the Error appears under this.

ruby -version:
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)

**Comment by Ekultek** [comment]
Use either ruby -v or ruby --version. It's parsing the -version into rsion.

Either of these two work. Count the number of dashes:

ruby -v
ruby --version
When you provide a single dash with "version", Ruby sees this:

ruby -v -e rsion

What I want you to do, attempt to install mechanize as a stand alone gen like you did before. Run `gem install mechanize --verbose`

**Comment by Shazgul** [comment]
ruby -v:
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]

Still the bundle install does not work... gem mechanize also not.

**Comment by Shazgul** [comment]
Full Output of gem install mechanize --verbose:

sudo gem install mechanize --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mechanize
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=domain_name,http-cookie,mime-types,net-http-digest_auth,net-http-persistent,nokogiri,ntlm-http,webrobots
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mime-types-data,mini_portile2,unf
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unf_ext
200 OK
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/.document
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/.gitignore
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/.travis.yml
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/CHANGELOG.md
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/Gemfile
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/LICENSE.txt
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/README.md
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/Rakefile
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/extconf.rb
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf.cc
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/normalizer.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/table.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/trie/char_stream.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/trie/node.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/trie/searcher.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext/unf/util.hh
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/lib/unf_ext.rb
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/lib/unf_ext/version.rb
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/test/helper.rb
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/test/normalization-test.txt
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/test/test_unf_ext.rb
/var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/unf_ext.gemspec
Building native extensions.  This could take a while...
current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20161129-1594-1vq6w0r.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'
ERROR:  Error installing mechanize:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/unf_ext-0.0.7.2/gem_make.out

**Comment by Ekultek** [comment]
Thank you let me do some research

**Comment by Shazgul** [comment]
Thank you, for your research, i'll hope there's an solution for me... :+1:

**Comment by Ekultek** [comment]
Alright, try this in this order:
`gem install nokogiri --pre`
`gem install nokogiri -v 1.6`
`gem install mechanize --verbose`

**Comment by Shazgul** [comment]
sudo gem install nokogiri --pre
Fetching: nokogiri-1.6.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.6.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20161129-3424-1y5cre8.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /usr/lib/ruby/2.3.0/mkmf.rb:522:in `with_werror'
	from /usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:139:in `nokogiri_try_compile'
	from extconf.rb:163:in `block in add_cflags'
	from /usr/lib/ruby/2.3.0/mkmf.rb:629:in `with_cflags'
	from extconf.rb:162:in `add_cflags'
	from extconf.rb:415:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/nokogiri-1.6.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.6.8.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86-linux/2.3.0/nokogiri-1.6.8.1/gem_make.out

**Comment by Shazgul** [comment]
Should i try to deinstall Ruby2.3 & Ruby via autoremove and install it again?

**Comment by Ekultek** [comment]
The issue is nokogiri is a pain in the fuckin ass to install, it's not just you it happens to everyone. Run these two commands and try to reinstall with the above commands:
`sudo apt-get install build-essential patch`
`sudo apt-get install ruby-dev zlib1g-dev liblzma-dev`

**Comment by Shazgul** [comment]
Actually it seems to work (the Installation) but nokogiri -v 1.6 command stucks at Installing ri documentation for nokogiri-1.6.0 for alot of minutes now. -pre worked awesome,full log:

sudo gem install nokogiri -v 1.6
Fetching: mini_portile-0.5.3.gem (100%)
Successfully installed mini_portile-0.5.3
Fetching: nokogiri-1.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.0
Parsing documentation for mini_portile-0.5.3
Installing ri documentation for mini_portile-0.5.3
Parsing documentation for nokogiri-1.6.0
unable to convert "\xE4" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/doc/examples/testWriter.c, skipping
unable to convert "\xF8" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/entities.c, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/result/HTML/doc3.htm, skipping
unable to convert "\xE9" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/runtest.c, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/test/HTML/doc3.htm, skipping
unable to convert "\xFC" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/test/HTML/wired.html, skipping
unable to convert "\xC0" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/test/XInclude/ents/isolatin.txt, skipping
unable to convert "\xF8" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxml2/2.8.0/libxml2-2.8.0/testapi.c, skipping
unable to convert "\xF6" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/ChangeLog, skipping
unable to convert "\xE1" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/NEWS, skipping
unable to convert "\xE4" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/configure.in, skipping
unable to convert "\xE1" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/doc/xslt.html, skipping
unable to convert "\xF6" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/libxslt/xslt.c, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/docbook/result/html/bib.html, skipping
unable to convert "\xA0" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/docbook/result/html/classsynop.html, skipping
unable to convert "\xA0" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/docbook/result/html/docbook40.html, skipping
unable to convert "\xA9" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/docbook/result/html/kwrite.html, skipping
unable to convert "\xED" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/docbook/result/html/multilingual.html, skipping
unable to convert "\xA0" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/xmlspec/REC-xml-20001006-review.html, skipping
unable to convert "\xA0" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/tests/xmlspec/REC-xml-20001006.html, skipping
unable to convert "\xFD" from ASCII-8BIT to UTF-8 for ext/nokogiri/tmp/i686-linux-gnu/ports/libxslt/1.1.26/libxslt-1.1.26/win32/Readme.txt, skipping
Installing ri documentation for nokogiri-1.6.0

**Comment by Ekultek** [comment]
Did the bundle install work?

**Comment by Shazgul** [comment]
it's still at the nokogiri stuff you've said there:

"Alright, try this in this order:
gem install nokogiri --pre
gem install nokogiri -v 1.6
gem install mechanize --verbose"

**Comment by Ekultek** [comment]
Oh okay well let's continue from there.
run `gem list noko`

**Comment by Shazgul** [comment]
After 31 Minutes "gem install nokogiri -v 1.6" was done. :D

now it's installing nokogiri 1.6.8 via "bundle install"... hope this will go faster now.
But bundle install seems to work now.

**Comment by Ekultek** [comment]
Yeah sounds about right. Nokogiri is a pain sometimes because of how it's built. I'm going to leave this open for a day or so and open it for questions. I'll also update the self help off of this. If you have anymore issues feel free to drop a comment. Enjoy the program and learn something from it, thanks for using it have a good one

**Comment by Shazgul** [comment]
First of all: It's workin' perfectly now! I'm really happy about this, now i've tried the -s command at a site of a friend (he allowed it to me) -> this was the result:

$ ruby whitewidow.rb -s http://sportquiz.ch/websoccer/
[04:11:03 INFO] Found https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css
[04:11:03 INFO] Found https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css
[04:11:03 INFO] Found https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css
[04:11:03 INFO] Found https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css
[04:11:04 INFO] Found a total of 135 links. Running them as file..
[04:11:06 INFO] Formatting file
[04:11:06 INFO] Writing to temporary file..

So it doesn't really gain the Redirects from this site, it's getting into bootstrapcdn and adobe.

**Comment by Ekultek** [comment]
I know that's still a work in progress, it recursively pulls the sites from the HTML. He best way to run the spider is run it through a site with a php tag, for example: `ruby whitewidow.rb -s http://example.com/php?id=1`. The spider is next in line to be upgraded. 

The reason it's pulling the bootstrap is because that specific site has a lot of bootstrapped css redirects in it. It'll catch a redirect and run from there so let's say you have the site above with a redirect to Facebook it'll grab the Facebook redirect and run there. It'll be fixed don't worry

**Comment by Shazgul** [comment]
Thanks for the Explanation i'll try my best :)!
Will there also be an feature to use post-data or even cookies :)?

**Comment by Ekultek** [comment]
I don't want to give away to much, but for the rest of the year you can expect the ability to run through tor, XSS checks, random search engines, the spider to do more, and a lot of styling upgrades. If you have ideas about things you'd like to see you can feel free to create issues for them and check the enhancement box. I'll give you one more, cookies are an extreme possibility

**Comment by Ekultek** [comment]
updated self help from this issue. Closing
