### ISSUE TITLE
Encoding errors with recursive spider

### ISSUE THREAD

**Issue by Shazgul** [Ekultek/whitewidow#30]
### Before you create an issue please make sure that there are no issues that relate to your issue you are trying to create, 
if there is an issue that relates to this, please add a comment to that one and describe your specific problem. There is
also a self help guide under the docs folder. Look through the troubleshooting and self help for help.
--

### Issue (be specific)
After a -s Scan on a Webpage, Whitewidow "encountered an error and cannot continue".. It totally stops the scan, also outputs a bunch of encoding errors

### Exact error message
ruby whitewidow.rb -s browsergames.info
[13:33:46 INFO] Found http://www.w3.org/1999/xhtml
[13:33:46 INFO] Found http://www.w3.org/2003/g/data-view
[13:33:46 INFO] Found http://www.w3.org/StyleSheets/TR/base
[13:33:46 INFO] Found http://www.w3.org/2008/07/rdfa-xslt
[13:33:46 INFO] Found http://www.w3.org/2003/g/data-view#
[13:33:47 INFO] Found http://www.w3.org/1999/xhtml
[13:33:47 INFO] Found http://www.w3.org/2008/07/rdfa-xslt
[13:33:47 INFO] Found http://www.w3.org/
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
[13:37:17 INFO] Found http://www.w3.org/1999/xhtml
[13:37:17 INFO] Found http://www.browsergames.info/index.php?a=out&u='
[13:37:18 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:18 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:18 INFO] Found http://www.browsergames.info/
[13:37:18 INFO] Found http://www.browsergames.info/
[13:37:18 INFO] Found http://www.browsergames.info/
[13:37:19 INFO] Found http://www.browsergames.info/index.php?a=join
[13:37:19 INFO] Found http://www.browsergames.info/index.php?a=user_cpl
[13:37:19 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=rlk
[13:37:19 INFO] Found http://js.adscale.de/getads.js
[13:37:19 INFO] Found http://js.adscale.de/getads.js
[13:37:20 INFO] Found http://www.facebook.com/pages/browsergamesinfo/240976396022694
[13:37:20 INFO] Found http://www.browsergames.info/index.php?a=page&amp;id=impressum
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
[13:37:23 INFO] Found http://www.facebook.com/pages/browsergamesinfo/240976396022694
[13:37:23 INFO] Found http://www.browsergames.info/index.php?a=page&amp;id=impressum
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
[13:37:28 INFO] Found http://www.w3.org/1999/xhtml
[13:37:28 INFO] Found http://www.browsergames.info/index.php?a=out&u='
[13:37:28 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:28 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:28 INFO] Found http://www.browsergames.info/
[13:37:29 INFO] Found http://www.browsergames.info/
[13:37:29 INFO] Found http://www.browsergames.info/
[13:37:29 INFO] Found http://www.browsergames.info/index.php?a=join
[13:37:29 INFO] Found http://www.browsergames.info/index.php?a=user_cpl
[13:37:29 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=rlk
[13:37:30 INFO] Found http://js.adscale.de/getads.js
[13:37:30 INFO] Found http://js.adscale.de/getads.js
[13:37:30 INFO] Found http://www.facebook.com/pages/browsergamesinfo/240976396022694
[13:37:30 INFO] Found http://www.browsergames.info/index.php?a=page&amp;id=impressum
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xB3 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
...
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0xFF 0xC3 0x98 0xC3
I/O error : encoder error
[13:37:42 INFO] Found http://www.w3.org/1999/xhtml
[13:37:43 INFO] Found http://www.browsergames.info/index.php?a=out&u='
[13:37:43 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:43 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=mafiakoenig
[13:37:43 INFO] Found http://www.browsergames.info/
[13:37:43 INFO] Found http://www.browsergames.info/
[13:37:44 INFO] Found http://www.browsergames.info/
[13:37:44 INFO] Found http://www.browsergames.info/index.php?a=join
[13:37:44 INFO] Found http://www.browsergames.info/index.php?a=user_cpl
[13:37:44 INFO] Found http://www.browsergames.info/index.php?a=out&go=1&u=rlk
[13:37:44 INFO] Found http://js.adscale.de/getads.js
[13:37:45 INFO] Found http://js.adscale.de/getads.js
[13:37:45 INFO] Found http://www.facebook.com/pages/browsergamesinfo/240976396022694
[13:37:45 INFO] Found http://www.browsergames.info/index.php?a=page&amp;id=impressum
encoding error : output conversion failed due to conv error, bytes 0xA2 0x3C 0x2F 0x70
I/O error : encoder error
encoding error : output conversion failed due to conv error, bytes 0x89 0x50 0x4E 0x47
I/O error : encoder error
[13:37:45 ERROR] browsergames.info encountered an error and cannot continue.

### Steps to reproduce
Make an Scan on browsergames.info

### Search query if applicable
-s browsergames.info

### Whitewidow version number
1.7.2.9

### Ruby version number
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]

### Labels

 - [X] Bug
 - [X] Encoding
 - [ ] Enhancement
 - [ ] Question
 - [ ] Email request

**Comment by Ekultek** [comment]
Alright, I'm extremely worried about the encoding errors. The reason it stops is that due to the errors caught with the spider, as of right now there's no way to rescue them. I'll be changing the rescue to were it will run the file as is, so if it hits the error all the sites it already has will be run. However the `IO` errors are extremely helpful and I can use this for my encoding issues.

**Comment by Ekultek** [comment]
All encoding that need to be fixed:

`set(['', '0x4E', '0x3C', '0x89', '0x50', '0xC3', '0x47', '0xFF', '0x70', 'xFF', '0x2F', '0xA2', '0xB3', '0x98'])`

**Comment by Shazgul** [comment]
I really wanna say thanks for all your work, i hope i'm not such a pain in your work because of my Installation-Problem first and now this...

**Comment by Ekultek** [comment]
@Shazgul You're good, I created it, it's my job to fix it's errors

**Comment by Ekultek** [comment]
characters, bytes and encoding details:

```
irb(main):048:0> data.each { |char| 
irb(main):049:1*   puts "Character: #{char}"
irb(main):050:1>   puts "Char length: #{char.chars.length}"
irb(main):051:1>   puts "Byte length: #{char.bytes.length}"
irb(main):052:1>   puts "Encoding: #{char.encoding}"
irb(main):053:1> }
Character: 0x4E
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x3C
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x89
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x50
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0xC3
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x47
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0xFF
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x70
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: xFF
Char length: 3
Byte length: 3
Encoding: UTF-8
Character: 0x2F
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0xA2
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0xB3
Char length: 4
Byte length: 4
Encoding: UTF-8
Character: 0x98
Char length: 4
Byte length: 4
Encoding: UTF-8
=> ["0x4E", "0x3C", "0x89", "0x50", "0xC3", "0x47", "0xFF", "0x70", "xFF", "0x2F", "0xA2", "0xB3", "0x98"]
```

**Comment by Ekultek** [comment]
From page source all characters are UTF-8: `<script src="/theme/menu/MenuMatic_0.68.3.js" type="text/javascript" charset="utf-8"></script>`

**Comment by Ekultek** [comment]
@Shazgul It took you that long and 3 issues to star my repo?! You sir are mean.. lol

**Comment by Ekultek** [comment]
Think I figured this out:

```
p data.map { |char|
  char.chr.encode('utf-8', invalid: :replace, undef: :replace)
}    #["N", "<", "\uFFFD", "P", "\uFFFD", "G", "\uFFFD", "p", "\uFFFD", "/", "\uFFFD", "\uFFFD", "\uFFFD"]


p data.map { |char|
  char.chr.encode('iso-8859-1', invalid: :replace, undef: :replace)
} #["N", "<", "?", "P", "?", "G", "?", "p", "?", "/", "?", "?", "?"]
```

**Comment by Ekultek** [comment]
temp fix:
```
irb(main):001:0> data = ["http://•google.com£.com", "http://americandad.net/php?id=©"]
=> ["http://•google.com£.com", "http://americandad.net/php?id=©"]
irb(main):002:0> data.each { |url|
irb(main):003:1*   arr = url.split('')
irb(main):004:1>   p arr.map { |char|
irb(main):005:2*     char.chr.encode("utf-8", invalid: :replace, undef: :replace)
irb(main):006:2>   }
irb(main):007:1> }
["h", "t", "t", "p", ":", "/", "/", "•", "g", "o", "o", "g", "l", "e", ".", "c", "o", "m", "£", ".", "c", "o", "m"]
["h", "t", "t", "p", ":", "/", "/", "a", "m", "e", "r", "i", "c", "a", "n", "d", "a", "d", ".", "n", "e", "t", "/", "p", "h", "p", "?", "i", "d", "=", "©"]
=> ["http://•google.com£.com", "http://americandad.net/php?id=©"]
```

All that's left to do is implement it into the source code

**Comment by Ekultek** [comment]
My little script didn't work, going back to the drawing board

**Comment by Ekultek** [comment]
Temp fix for this issue in next push:
`data = Settings::ProgramSettings.new.parse(url, 'html', 0).encode("utf-8", invalid: :replace, undef: :replace)`

**Comment by Ekultek** [comment]
New release has been pushed with temp fix, if you find any errors post them here.

**Comment by Ekultek** [comment]
Fixed with latest pull request, thank you @TylerRockwell you beastly mother fucker you
