### ISSUE TITLE
Use a full path name drop Dir.pwd

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#4]
Running:

```
ruby whitewidow.rb -f /tmp/scan.txt 
```

Produces:

```
whitewidow.rb:233:in `read': No such file or directory @ rb_sysopen - /home/unshadow/Desktop/git-projects/whitewidow//tmp/scan.txt (Errno::ENOENT)
    from whitewidow.rb:233:in `begin_vulnerability_check'
    from whitewidow.rb:302:in `<main>'
```

Whitewidow decides that the file is in the same dir, sometimes it's not.

**Comment by Ekultek** [comment]
Negative, get rid of the beginning / and use tmp/scan.txt.

/tmp/scan.txt <= INCORRECT
tmp/scan.txt <= CORRECT

Check the help section and read the comments.

**Comment by Ekultek** [comment]
Read the comments, you don't need the beginning slash, I've made it so that t already has one so all you gotta do is specify the directory
