### ISSUE TITLE
require_relative: command not found

### ISSUE THREAD

**Issue by mienv567** [Ekultek/whitewidow#53]
./whitewidow.rb: line 3: require_relative: command not found
./whitewidow.rb: line 8: def: command not found
./whitewidow.rb: line 9: syntax error near unexpected token `"ruby #{File.basename(__FILE__)} -[OPTIONS] --[OPTIONAL-OPTIONS]"'
./whitewidow.rb: line 9: `  FORMAT.info("ruby #{File.basename(__FILE__)} -[OPTIONS] --[OPTIONAL-OPTIONS]")'

**Comment by Ekultek** [comment]
Find the full issue template in tmp/issues and post it please, thank you. I will close this in 48 hours if no response is given.

**Comment by Ekultek** [comment]
Closing due to no response
