### ISSUE TITLE
URL Connection Errors

### ISSUE THREAD

**Issue by bararchy** [Ekultek/whitewidow#6]
![screenshot from 2016-04-09 11-02-20](https://cloud.githubusercontent.com/assets/1631073/14402569/97b4f48c-fe42-11e5-876f-247ccec01625.png)

**Comment by Ekultek** [comment]
......

**Comment by Ekultek** [comment]
Alright, here's what I'm going to do,I'm gonna make a log that will extract these and throw them into a different file, from there it will read through the file and if the lines in the file match any of the URLs skip them. I think this will work.

**Comment by Ekultek** [comment]
The reason these sites are connecting is because they're closed properly and redirect to a whitescreen. This issue will be closed.
