### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by kali64amd** [Ekultek/whitewidow#62]
I'm getting this error while installing.............

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.

**Comment by Ekultek** [comment]
This is just a bundler warning, my guess is that you're the only one on your system and you're the root user, so don't worry about it just run `bundle install` and you'll be fine. I'll close this after you reply.

**Comment by Ekultek** [comment]
closing 24 hours no response
