### ISSUE TITLE
Country specific search queries test log

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#7]
I'm opening this issue due to adding 40 country specific search queries, there are 20 co.uk, and 20.ng I want to keep a log on how well they go as to decide whether or not to incorporate country specific queries into whitewidow. If you get a run of one of them, post here and let me know how they went, pictures would be greatly appreciated.

**Comment by bararchy** [comment]
What's the Syntax for specifying the country suffix ?

**Comment by Ekultek** [comment]
Check the search_queries.txt file and search for .ng, and .co.uk

**Comment by Ekultek** [comment]
Will be adding more country specific dorks

**Comment by Ekultek** [comment]
RE-OPENED 09/08/2016
