### ISSUE TITLE
screwed up formatting "cyan for nil class"

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#71]
![issue_9](https://cloud.githubusercontent.com/assets/14183473/26289413/7b9020ce-3e65-11e7-8e16-6cd7812cd5da.PNG)
![issue_9_9](https://cloud.githubusercontent.com/assets/14183473/26289415/7dd675e0-3e65-11e7-8e19-e3bb95a00c73.PNG)

**Comment by Drever23** [comment]
I have the same problem. I can not understand how to fix it.
