### ISSUE TITLE
Cant install restclient

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#73]
Hi @Ekultek 
I have this error 
"opt/whitewidow/lib/imports/constants_and_requires.rb:6:in `require': cannot load such file -- rest-client (LoadError)
	from /opt/whitewidow/lib/imports/constants_and_requires.rb:6:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'
"
And I tried to install again rest-client

"gem install rest-client
Successfully installed rest-client-2.0.2
Parsing documentation for rest-client-2.0.2
Done installing documentation for rest-client after 0 seconds
1 gem installed"

Additional 
ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

Any comment?

Thanks

From #55

**Comment by Ekultek** [comment]
`gem install restclient` that should do that job

**Comment by smtabakoglu** [comment]
I did but 

gem install restclient
Fetching: paint-1.0.1.gem (100%)
Successfully installed paint-1.0.1
Fetching: restclient-0.14.4.gem (100%)
restclient's executable "restclient" conflicts with rest-client
Overwrite the executable? [yN]  y
!    The 'restclient' gem has been deprecated and has been replaced by 'restup'.
!    See: https://rubygems.org/gems/restup
!    And: https://github.com/thoom/restup
Successfully installed restclient-0.14.4
Parsing documentation for paint-1.0.1
Installing ri documentation for paint-1.0.1
Parsing documentation for restclient-0.14.4
Installing ri documentation for restclient-0.14.4
Done installing documentation for paint, restclient after 0 seconds
2 gems installed

Still same

ruby whitewidow.rb 
/opt/whitewidow/lib/imports/constants_and_requires.rb:6:in `require': cannot load such file -- rest-client (LoadError)
	from /opt/whitewidow/lib/imports/constants_and_requires.rb:6:in `<top (required)>'
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'

**Comment by Ekultek** [comment]
Wait a second, did you do `bundle install`?

**Comment by smtabakoglu** [comment]
Yeah,already did it before

bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using addressable 2.4.0
Using safe_yaml 1.0.4
Using diff-lcs 1.2.5
Using unf_ext 0.0.7.2
Using hashdiff 0.3.0
Using mime-types-data 3.2016.0521
Using net-http-digest_auth 1.4
Using net-http-persistent 2.9.4
Using pkg-config 1.1.7
Using ntlm-http 0.1.1
Using webrobots 0.1.2
Using mini_portile2 2.1.0
Using rspec-support 3.5.0
Using vcr 3.0.0
Using bundler 1.12.5
Using crack 0.4.3
Using unf 0.1.4
Using mime-types 3.1
Using nokogiri 1.6.8
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using webmock 1.24.2
Using domain_name 0.5.20160615
Using rspec 3.5.0
Using http-cookie 1.0.2
Using mechanize 2.7.5
Bundle complete! 6 Gemfile dependencies, 27 gems now installed.

**Comment by Ekultek** [comment]
Something's wrong with your installation, uninstall `rest-client` and `restclient`, along with `nokogiri` after you've done all that run `gem install rest-client -v 2.0` and then run `bundle install`

**Comment by Ekultek** [comment]
This seems to be OS specific, here's an example of running on Debian, and on Windows 7, it works on the MS platform but not on the Debian platform. What OS are you running?

![whitewidow-issue](https://cloud.githubusercontent.com/assets/14183473/26700450/feac0b28-46e2-11e7-8772-9ba8c78b41db.PNG)

**Comment by smtabakoglu** [comment]
@Ekultek Kali 2016.1 version 

_Sent from my ZTE A2017G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Ekultek** [comment]
Kali is a Debian distro right?

**Comment by Ekultek** [comment]
Try one more thing for me, `sudo apt-get install ruby-rest-client`

**Comment by Ekultek** [comment]
@noptrix have you experienced this on blackarch?

**Comment by Ekultek** [comment]
Is Kali a Debian distro?

- Thomas Perkins

**Comment by smtabakoglu** [comment]
Yes,I think so :)

By the way i also tried with another kali instance but no luck!

![image](https://cloud.githubusercontent.com/assets/15263586/26717201/2af2a956-4785-11e7-9cbc-7bad61ca1203.png)
![image](https://cloud.githubusercontent.com/assets/15263586/26717220/443105ac-4785-11e7-8f08-1b696de0e956.png)
![image](https://cloud.githubusercontent.com/assets/15263586/26717239/55a0063a-4785-11e7-91cd-34aa8ce82650.png)

![image](https://cloud.githubusercontent.com/assets/15263586/26717248/60a6e81e-4785-11e7-9327-bb868cf116df.png)

**Comment by Ekultek** [comment]
Alright one more ditch effort, delete the gem.lock file and run `bundle install`

**Comment by smtabakoglu** [comment]
I did this actions
![image](https://cloud.githubusercontent.com/assets/15263586/26724811/0db6d9f6-47a4-11e7-8710-9644398d7c17.png)

Result is same
![image](https://cloud.githubusercontent.com/assets/15263586/26724825/2138aae0-47a4-11e7-9fb9-200c320fc758.png)

Anyway thank you for your patience.I will try qith different OS

**Comment by Ekultek** [comment]
Completely delete the lock file and try again, also try with a different OS like you said and I'll see what I can figure out

**Comment by Ekultek** [comment]
Also try upgrading bundler, that might be the issue as well

**Comment by noptrix** [comment]
@Ekultek sorry for the delayed response...too busy atm. no, i didn't have the error like above.

**Comment by AintCoolSon** [comment]
Duh, I'm having the same issue. Did everything required and still no luck. 
I'll be online all day. Lets solve this

**Comment by Ekultek** [comment]
Alright, what operating systems have you tried so far?

**Comment by AintCoolSon** [comment]
I'm using the latest and greatest version of Parrot OS.

**Comment by Ekultek** [comment]
Lol that's what's up, alright ima push a test branch to the repo and I want you to clone from that branch and try it, gimme a couple minutes

**Comment by Ekultek** [comment]
Clone from this branch https://github.com/WhitewidowScanner/whitewidow/tree/test-branch and try it

**Comment by AintCoolSon** [comment]
Done that.
/whitewidow/lib/imports/constants_and_requires.rb:195:in `<top (required)>': uninitialized constant RestClient::NotFound (NameError)
	from whitewidow.rb:2:in `require_relative'
	from whitewidow.rb:2:in `<main>'

**Comment by Ekultek** [comment]
so you did `git clone -b test-branch https://github.com/ekultek/whitewidow.git`?

**Comment by AintCoolSon** [comment]
^Nvm. Works now. /thread

**Comment by Ekultek** [comment]
Works?

**Comment by noptrix** [comment]
@Ekultek jfyi, on blackarch no problem.

**Comment by AintCoolSon** [comment]
Yeah, it works. Running it rn.

**Comment by Ekultek** [comment]
@noptrix cool, thanks man
@AintCoolSon awesome, closing the down with the next push

**Comment by Ekultek** [comment]
Fixed via f50bd02 

@noptrix I'm closing yours down as well
