### ISSUE TITLE
Using dork feature

### ISSUE THREAD

**Issue by AintCoolSon** [Ekultek/whitewidow#74]
The tool does 'well', running on defaults, however, when I try to use custom dorks using -D or --dork, the tool crashes.
$ruby whitewidow.rb --dork "inurl:php?id= site:rs" 

No error message shown. Am I using this feature wrong?

**Comment by Ekultek** [comment]
`ruby whitewidow.rb -d -D <DORK>`

The crash happens because you're running a valid argument but not telling it what to do.
