### ISSUE TITLE
Note: Kali 4.9 Requirements

### ISSUE THREAD

**Issue by sbridgens** [Ekultek/whitewidow#75]
Note in order to successfully install this on kali 4.9:

1: apt-get install liblzma-dev zlib1g-dev
2: gem install nokogiri -v '1.8.0' -V
3: bundle install

be good to add to the readme..

**Comment by Ekultek** [comment]
So add it? And if you don't know how to install this on Kali, you shouldn't be using Kali.

**Comment by Ekultek** [comment]
fixed via ed98962

**Comment by sbridgens** [comment]
thanks was being helpful, dick comment btw.

**Comment by Ekultek** [comment]
Not a dick comment, just pointing out you're capable of adding it as well, and then you'd be a contributor and go on my special contributions list 

- Thomas Perkins

**Comment by sbridgens** [comment]
thanks will do so in future
