### ISSUE TITLE
g9XdKhe undefined method `set_proxy' for #<String:0x005653ec3880d8>

### ISSUE THREAD

**Issue by jopcode** [Ekultek/whitewidow#77]
[![asciicast](https://asciinema.org/a/128493.png)](https://asciinema.org/a/128493)

## Issue/Enhancement/Question (be specific)
Getting error: undefined method `set_proxy' for #<String:0x005653ec3880d8>

## Exact error message/Enhancement information
undefined method `set_proxy' for #<String:0x005653ec3880d8>

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true, :proxy=>"204.13.204.110:8080"}

## Search query if applicable (please use exact search query)
print.php?goto=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0.6.6

## Ruby version number (run ruby --version)
2.3.3

## Error log information
2017-07-11
["/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/root/whitewidow/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]

**Comment by Ekultek** [comment]
That's interesting, try a different proxy please

**Comment by jopcode** [comment]
@Ekultek I already tried with another 6 proxies and give me same error.

**Comment by Ekultek** [comment]
Hmm.. Try, `https://<proxy>`

**Comment by jopcode** [comment]
Ok, now give me that:


## Issue/Enhancement/Question (be specific)
Getting error: Failed to open TCP connection to https:80 (getaddrinfo: Name or service not known)

## Exact error message/Enhancement information
Failed to open TCP connection to https:80 (getaddrinfo: Name or service not known)

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true, :agent=>true, :proxy=>"https://139.59.243.186:80"}

## Search query if applicable (please use exact search query)
general.php?doshow=


## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0.6.6

## Ruby version number (run ruby --version)
2.3.3

## Error log information
2017-07-11
["/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'", "/var/lib/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:586:in `submit'", "/root/whitewidow/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]

**Comment by Ekultek** [comment]
Alright that makes more sense. Give me a little bit to look into it

**Comment by Ekultek** [comment]
Working on this right now

**Comment by jopcode** [comment]
@Ekultek Nice!, I am also working on a project right now, I will be attentive to any response

**Comment by Ekultek** [comment]
From what I can see it seems like the proxy you were trying to use is bad. When you pass a proxy you need to verify what kind of proxy it is, socks, http, https, etc.. Otherwise it just assumes that there's a string there. That's where the `#<String:0x005653ec3880d8>` is coming from. It's the spot in memory were the string is sitting. I'd really suggest you just use a VPN over a proxy.

**Comment by Ekultek** [comment]
HOWEVER, I can't seem to get `unf_ext` installed on my system right now so lemme figure out how to get that installed and I'll double check everything lol

**Comment by Ekultek** [comment]
Use a good proxy and use it in this format `(socks\d+|http(s)?)<IP-ADDR>:<PORT#>`

**Comment by jopcode** [comment]
@Ekultek  oks (:

**Comment by Ekultek** [comment]
No reports of any problems in a week, closing
