### ISSUE TITLE
 undefined method `cyan' for nil:NilClass

### ISSUE THREAD

**Issue by rexortas** [Ekultek/whitewidow#81]
## Issue/Enhancement/Question (be specific)
Getting error: undefined method `cyan' for nil:NilClass

## Exact error message/Enhancement information
undefined method `cyan' for nil:NilClass

## Steps to reproduce if applicable or steps on what should be done
Run with {:file=>"/home/username/Downloads/Private.txt"}

## Search query if applicable (please use exact search query)
N/A

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0.7.7

## Ruby version number (run ruby --version)
2.4.2

## Error log information
2017-09-24
---
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---
2017-09-25
---
["/usr/share/whitewidow/lib/whitewidow/scanner.rb:127:in `read'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:127:in `prepare_file_flag_file'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:12:in `format_file'", "whitewidow.rb:102:in `<main>'"]
["/usr/share/whitewidow/lib/whitewidow/scanner.rb:127:in `read'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:127:in `prepare_file_flag_file'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:12:in `format_file'", "whitewidow.rb:102:in `<main>'"]
---
2017-09-25
---
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---
2017-09-25
---
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---
2017-09-25
---
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---
2017-09-25
---
["/usr/share/whitewidow/lib/modules/core/format.rb:27:in `write'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `puts'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `puts'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `err'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:101:in `rescue in block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:79:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:27:in `write'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `puts'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `puts'", "/usr/share/whitewidow/lib/modules/core/format.rb:27:in `err'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:101:in `rescue in block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:79:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---
2017-09-28
---
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
["/usr/share/whitewidow/lib/modules/core/format.rb:52:in `site_found'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:85:in `block (2 levels) in vulnerability_check'", "/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:81:in `block in vulnerability_check'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `each_line'", "/usr/share/whitewidow/lib/whitewidow/scanner.rb:78:in `vulnerability_check'", "whitewidow.rb:103:in `<main>'"]
---

It scans several links and this error occurs. Prompt in what a problem? Thank you

**Comment by Ekultek** [comment]
Use Zeus for now https://github.com/ekultek/Zeus-Scanner
