### ISSUE TITLE
How many of you think I should keep this going?

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/whitewidow#82]
Comment or react to this issue if you want the development to continue

**Comment by VAllens** [comment]
Hi, Ekultek. :)

I think it's a great open source project.
I hope you will continue to develop.

Thanks so much.

**Comment by coderxani** [comment]
Hi,
just followed you now.

nice job you are doing here.

i sent you an email. that need urgent attention. kindly check. 
from.
ecoder2020@gmail.com

**Comment by Ekultek** [comment]
@coderxani replied.

**Comment by CodeSlemming** [comment]
Hello,

I'd like to tell you what a good job you are making. I admit your standard build are a really nice tool and I have made some private forks of it (For myself..) If you ever discountiue this project I would like to keep it running. It benefits a load of people, even people doing it for ethical purposes. 

Sorry for any spelling mistakes, english is not my first language. (Russian)

**Comment by Ekultek** [comment]
@xKeyScores do you have a discord?

**Comment by CodeSlemming** [comment]
yes, add xKeyScore#7371

**Comment by Ekultek** [comment]
@xKeyScores for some reason that's not working add me Salty#4256

**Comment by Ekultek** [comment]
@xKeyScores added

**Comment by picepice** [comment]
Nice..

**Comment by coderxani** [comment]
@ekultek
  my email awaits your response.
 please kindly let me know your needs.
  i need it done in 3days time.

**Comment by Ekultek** [comment]
Been two weeks, 5 out of 73 followers is not enough.
