### ISSUE TITLE
Failed with error code U+1EDB from UTF-8 to ISO-8859-1

### ISSUE THREAD

**Issue by hnhhl** [Ekultek/whitewidow#83]
#errror 
[08:23:30 INFO] I'm searching for possible SQL vulnerable sites, using search query inurl:/allindex2.php?f=
[08:23:30 INFO] Using default user agent
[08:23:30 INFO] Verifying search query...
[08:23:30 ERROR] Failed with error code U+1EDB from UTF-8 to ISO-8859-1
[08:23:30 FATAL] Program failed with error code: U+1EDB from UTF-8 to ISO-8859-1, error saved to error_log.txt
[08:23:30 FATAL] Issue template is being generated for this error, create a new issue named: KFnd8Qh U+1EDB from UTF-8 to ISO-8859-1
[08:23:30 INFO] An issue template has been generated for you and is located in C:/Users/Vn cracker/Desktop/whitewidow-master/tmp/issues/Uo21z9Q.txt

#logs 
## Issue/Enhancement/Question (be specific)
Getting error: U+1EDB from UTF-8 to ISO-8859-1

## Exact error message/Enhancement information
U+1EDB from UTF-8 to ISO-8859-1

## Steps to reproduce if applicable or steps on what should be done
Run with {:default=>true}

## Search query if applicable (please use exact search query)
inurl:/allindex2.php?f=

## User agent (if applicable)
N/A

## Whitewidow version number (must have the actual version run `ruby whitewidow.rb --version`)
2.0.7.7

## Ruby version number (run ruby --version)
2.4.4

## Error log information
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---
2018-06-03
---
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
["C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `encode'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/util.rb:77:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:291:in `from_native_charset'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:285:in `block in proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `map'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:284:in `proc_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:347:in `block in build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `each'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:346:in `build_query'", "C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mechanize-2.7.6/lib/mechanize.rb:587:in `submit'", "C:/Users/Vn cracker/Desktop/whitewidow-master/lib/whitewidow/scanner.rb:50:in `get_urls'", "whitewidow.rb:64:in `<main>'"]
---

**Comment by Ekultek** [comment]
This project is no longer maintained.
