### ISSUE TITLE
unknown escape character

### ISSUE THREAD

**Issue by devilmind81** [Ekultek/whitewidow#84]
I have cloned the repo and executed bundle install command from the root folder.

After trigger ruby whitewidow.rb .d I'm obtaining:

## Issue/Enhancement/Question (be specific)
Getting error: (/home/parrot/whitewidow/lib/lists/inject.yml): found unknown escape character while parsing a quoted scalar at line 19 column 19

Can you help me please?

**Comment by JackandBlackLLL** [comment]
some mistake

**Comment by psychomad** [comment]
Had same prob. I arrange to use tool put "#" on two lines

 - " AND EXTRACTVALUE('[rand_num]']',CONCAT('\','[del_start]',(SELECT (ELT('[rand_num]'='[rand_num]',1))),'[del_stop]'))"

- " OR EXTRACTVALUE('[rand_num]',CONCAT('\','[del_start]',(SELECT (ELT('[rand_num]'='[rand_num]',1))),'[del_stop]'))"

At the moment im try to figure out how to fix
